repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.12.9

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: local
    hooks:
      - id: run-tests
        name: Run tests and coverage before push
        entry: ./scripts/pre_push_check.sh
        language: system
        always_run: true
        pass_filenames: false
