name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  PYTHONPATH: ${{ github.workspace }}
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      JWT_SECRET_KEY: ${{ vars.JWT_SECRET_KEY }}
      FRONT_REDIRECT_URI: ${{ vars.FRONT_REDIRECT_URI }}
      MOVIE_API_KEY: ${{ vars.MOVIE_API_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv (Python dependency manager)
        run: |
          curl -Ls https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync dependencies with uv
        run: |
          uv sync

      - name: Run pre-push checks
        run: ./scripts/pre_push_check.sh

      - name: Run tests with coverage
        run: |
          uv run pytest --cov --cov-branch --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
